name: GitHub Pages

on:
  push:
    branches: [main]
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install
        run: npm ci
      - name: Build and Deploy
        env:
          NODE_ENV: production
          # Remove this line if you would like to skip using google analytics
          REACT_APP_GA_TRACKING_ID: UA-68649021-1
          # This is set automatically by github
          GITHUB_TOKEN: ${{ secrets.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 }}
        run: |
          git config user.name "Automated"
          git config user.email "gilserrant5@gmail.com"
          git remote set-url origin https://git:${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}@github.com/G-Tech1/personal-site.git
          npm run deploy
